### ISSUE TITLE
[Bug Report] Blank project page when networks are listed as keys

### ISSUE THREAD

**Issue by RafGamer** [Yacht-sh/Yacht#646]
**Describe the bug**
The project details page of a project is blank and the browser console throws a bunch of errors if the compose file has keys under networks instead of an array.

**To Reproduce**
1. Add a project with a compose file that lists the networks as keys.
2. Blank project details page and a bunch of errors in browser console.

**Expected behavior**
The project details page is shown correctly.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Yacht Version: v0.0.7-alpha-2023-01-12--05

**Additional context**
Seems like the parsing doesnt work correctly and the page is blank.

Example:

This compose file is shown without problems:

```
version: "3.8"

services:
  test:
    image: test/test
    container_name: test
    networks:
      - test
    restart: unless-stopped
```

This not:

```
version: "3.8"

services:
  test:
    image: test/test
    container_name: test
    networks:
      test:
    restart: unless-stopped
```
